dependencies:
- name: mongodb-replicaset
  version: "3.9.6"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: kafka
  version: 0.9.6
  repository: "http://storage.googleapis.com/kubernetes-charts-incubator"