apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gwas-depo-logs
  namespace: gwas-dev
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 1Gi
